name: Cypress Registration Script

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        with:
          install: true
          runTests: true
          command: npm run test:registration

      - name: Upload Mochawesome HTML Report
        uses: actions/upload-artifact@v4
        with:
          name: Mochawesome HTML Report
          path: cypress/reports/html
